#!/bin/bash

DATA_DIR=$1
#python3 atpboost.py \
#./dist/atpboost/atpboost \
./bin/dist/atpboost/atpboost \
	--problems $DATA_DIR/problems_outputs \
	--train_problems $DATA_DIR/train_problems_outputs \
	--train_deps $DATA_DIR/train_deps \
	--available_deps $DATA_DIR/available_deps_files \
	--statements $DATA_DIR/statements \
    --features $DATA_DIR/features \
	--ml_models xgboost \
	--xgb_rounds 20 \
	--mining 0 \
	--proving_script prove-fast.sh \
    --data_dir $DATA_DIR/atpboost_data \
    --n_jobs -1 \
	--logfile $DATA_DIR/atpboost.log

