#!/bin/bash

BATCH_SPEC=$1
OUT_DIR=$2

BATCH_SPEC_DIR=`dirname $BATCH_SPEC`

PROBLEMS_TYPES_ATP="+1 +2" # TODO change it; also be careful with spec. symb.

#module load python/python36 # TODO uncomment
DATA_DIR=`pwd`/data/CASC_SAMPLE; mkdir -p $DATA_DIR
# TODO change it to this:
#DATA_DIR=`mktemp -d`


TRAIN_ARCHIVE=$BATCH_SPEC_DIR/`grep division.category.training_data $BATCH_SPEC | cut -d' ' -f2`
tar xzf $TRAIN_ARCHIVE -C $DATA_DIR

SOLUTIONS_DIR=$DATA_DIR/Solutions
PROBLEMS_DIR=$DATA_DIR/Problems
# TODO make sure that both training and testing problems are in PROBLEMS_DIR
AXIOMS_DIR=$DATA_DIR/Axioms # TODO remember to use axioms

MINING_DIR=$DATA_DIR/MiningProofs
mkdir -p $MINING_DIR
for t in $PROBLEMS_TYPES_ATP; do
	find $DATA_DIR/Problems -name '*'$t'*.p' > $DATA_DIR/train_problems__$t
done
cat $DATA_DIR/train_problems__* > $DATA_DIR/train_problems
cat $DATA_DIR/train_problems | xargs -l1 basename \
	> $DATA_DIR/train_problems_basenames
paste -d' ' $DATA_DIR/train_problems \
	<(sed 's#^#'$MINING_DIR'/#g; s/.p$//g' $DATA_DIR/train_problems_basenames) \
	> $DATA_DIR/train_problems_outputs

sed -n '/SZS start BatchProblems/,/SZS end BatchProblems/p' $BATCH_SPEC \
	| grep -v '^%' > $DATA_DIR/problems_outputs
sed -i 's# # '$OUT_DIR'\/#g; s#^#'$BATCH_SPEC_DIR'\/#g' $DATA_DIR/problems_outputs
for t in $PROBLEMS_TYPES_ATP; do
	sed 's/\*/'$t'/g' $DATA_DIR/problems_outputs > $DATA_DIR/problems_outputs__$t
done
cat $DATA_DIR/problems_outputs__* | sort > $DATA_DIR/problems_outputs
cut -d' ' -f1 $DATA_DIR/problems_outputs | xargs cp -t $PROBLEMS_DIR
rm $DATA_DIR/problems_outputs__*

for t in $PROBLEMS_TYPES_ATP; do
	find $SOLUTIONS_DIR -name '*.s' | grep $t | grep 'E-' > $DATA_DIR/solutions_list__$t
done
cat $DATA_DIR/solutions_list__* > $DATA_DIR/solutions_list
rm $DATA_DIR/solutions_list__*
python3 deps.py $DATA_DIR/solutions_list > $DATA_DIR/train_deps_files
cut -d':' -f1,2 $DATA_DIR/train_deps_files > $DATA_DIR/train_deps
# TODO sort -u ?

for t in $PROBLEMS_TYPES_ATP; do
	find $PROBLEMS_DIR -name '*'$t'*.p' > $DATA_DIR/problems_list__$t
done
cat $DATA_DIR/problems_list__* > $DATA_DIR/problems_list
rm $DATA_DIR/problems_list__*
python3 prepare_statements.py $DATA_DIR/problems_list > $DATA_DIR/statements

python3 deps.py $DATA_DIR/problems_list > $DATA_DIR/available_deps_files
# TODO sort -u ?
cd featurizer
./featurize.pl $DATA_DIR/statements
cd ..
mv featurizer/features_enigma_as_axioms $DATA_DIR/features

#source atpboost_venv/bin/activate
# TODO run atpboost

# TODO remove tmp data
