#!/bin/bash


BATCH_SPEC=$1
OUT_DIR=$2

#module load python/python36
#DATA_DIR=data_casc
#mkdir $DATA_DIR
#
#TRAIN_DATA=`grep division.category.training_data $BATCH_SPEC | cut -d' ' -f2`
#
#tar xzf $TRAIN_DATA -C $DATA_DIR


DATA_DIR=`pwd`/LTB_CASC_26

SOLUTIONS_DIR=$DATA_DIR/Solutions
PROBLEMS_DIR=$DATA_DIR/Problems
# TODO make sure that both training and testing problems are in PROBLEMS_DIR
AXIOMS_DIR=$DATA_DIR/Axioms
# TODO remember to use axioms

find $SOLUTIONS_DIR -name '*.s' | grep 'E-' > $DATA_DIR/solutions_list
python3 deps.py $DATA_DIR/solutions_list > $DATA_DIR/train_deps

find $PROBLEMS_DIR -name '*+1*.p' > problems_list # TODO change +1
python3 prepare_statements.py problems_list > $DATA_DIR/statements

cd featurizer
./featurize.pl $DATA_DIR/statements
cd ..
mv featurizer/features_enigma_as_axioms $DATA_DIR/features

./atpboost.py \
	--conjectures data/MPTP2078/conjectures \
	--train_deps data/MPTP2078/train_deps \
	--statements data/MPTP2078/statements \
    --features data/MPTP2078/features_binary \
    --chronology data/MPTP2078/chronology \
	--ml_models xgboost \
    --data_dir data/MPTP2078/atpboost_data \
	--logfile `echo $0 | sed 's/\.sh/.log/g'`


