#!/bin/bash

BATCH_SPEC=$1
OUT_DIR=$2

BATCH_SPEC_DIR=`dirname $BATCH_SPEC`

#PROBLEMS_TYPES_ATP="+1 +2"
#PROBLEMS_TYPES_ATP="+4 +5 _4 _5"
PROBLEMS_TYPES_ATP="+4 +5"

#DATA_DIR=`mktemp -d`
DATA_DIR=/local1/bartosz/atpboost_tmp
mkdir $DATA_DIR
echo "Temporary data dir: "$DATA_DIR

TRAIN_ARCHIVE=$BATCH_SPEC_DIR/`grep division.category.training_data $BATCH_SPEC | cut -d' ' -f2`
tar xzf $TRAIN_ARCHIVE -C $DATA_DIR

SOLUTIONS_DIR=$DATA_DIR/Solutions
PROBLEMS_DIR=$DATA_DIR/Problems

MINING_DIR=$DATA_DIR/MiningProofs
mkdir -p $MINING_DIR
for t in $PROBLEMS_TYPES_ATP; do
	find $DATA_DIR/Problems -name '*'$t'*.p' > $DATA_DIR/train_problems__$t
done
cat $DATA_DIR/train_problems__* > $DATA_DIR/train_problems
cat $DATA_DIR/train_problems | xargs -l1 basename \
	> $DATA_DIR/train_problems_basenames
paste -d' ' $DATA_DIR/train_problems \
	<(sed 's#^#'$MINING_DIR'/#g; s/.p$//g' $DATA_DIR/train_problems_basenames) \
	> $DATA_DIR/train_problems_outputs

sed -n '/SZS start BatchProblems/,/SZS end BatchProblems/p' $BATCH_SPEC \
	| grep -v '^%' > $DATA_DIR/problems_outputs
sed -i 's# # '$OUT_DIR'\/#g; s#^#'$BATCH_SPEC_DIR'\/#g' $DATA_DIR/problems_outputs
for t in $PROBLEMS_TYPES_ATP; do
	sed 's/\*/'$t'/g' $DATA_DIR/problems_outputs > $DATA_DIR/problems_outputs__$t
done
cat $DATA_DIR/problems_outputs__* | sort > $DATA_DIR/problems_outputs
cut -d' ' -f1 $DATA_DIR/problems_outputs | xargs cp -t $PROBLEMS_DIR
rm $DATA_DIR/problems_outputs__*

for t in $PROBLEMS_TYPES_ATP; do
	find $SOLUTIONS_DIR -name '*.s' | grep $t | grep 'E-' > $DATA_DIR/solutions_list__$t
done
cat $DATA_DIR/solutions_list__* > $DATA_DIR/solutions_list
rm $DATA_DIR/solutions_list__*
python3 deps.py $DATA_DIR/solutions_list > $DATA_DIR/train_deps_files
cut -d':' -f1,2 $DATA_DIR/train_deps_files > $DATA_DIR/train_deps

for t in $PROBLEMS_TYPES_ATP; do
	find $PROBLEMS_DIR -name '*'$t'*.p' > $DATA_DIR/problems_list__$t
done
cat $DATA_DIR/problems_list__* > $DATA_DIR/problems_list
rm $DATA_DIR/problems_list__*
python3 prepare_statements.py $DATA_DIR/problems_list > $DATA_DIR/statements

PROBLEM_1=`head -1 $DATA_DIR/problems_outputs | cut -d' ' -f1`
AXIOMS_1_DIR=`dirname $PROBLEM_1`/Axioms
AXIOMS_2_DIR=$BATCH_SPEC_DIR/Axioms
mkdir -p $DATA_DIR/atpboost_data/problems
cp -r $AXIOMS_1_DIR $DATA_DIR/atpboost_data/problems 2> /dev/null
cp -r $AXIOMS_2_DIR $DATA_DIR/atpboost_data/problems 2> /dev/null

echo "# Featurizing..."
python3 deps.py $DATA_DIR/problems_list > $DATA_DIR/available_deps_files
cd featurizer
./featurize.pl $DATA_DIR/statements
cd ..
mv featurizer/features_enigma_as_axioms $DATA_DIR/features
rm -r featurizer/mfeat_*
echo "# Featurizing done."

./dist/atpboost/atpboost \
	--problems $DATA_DIR/problems_outputs \
	--train_problems $DATA_DIR/train_problems_outputs \
	--train_deps $DATA_DIR/train_deps \
	--available_deps $DATA_DIR/available_deps_files \
	--statements $DATA_DIR/statements \
    --features $DATA_DIR/features \
	--ml_models xgboost \
	--xgb_rounds 1000 \
	--xgb_rounds_increase 500 \
	--mining 0.2 \
	--proving_script prove.sh \
    --data_dir $DATA_DIR/atpboost_data \
    --n_jobs -1 \
	--logfile $DATA_DIR/atpboost.log

rm -rf $DATA_DIR
